### ISSUE TITLE
research storage options for the enzyme database feature

### ISSUE THREAD

**Issue by e0** [MetabolicAtlas/MetabolicAtlas#1008]
**Please describe the feature**

As a developer, I want to research options for the enzyme database feature so that I help ensure the data can be presented fast enough and is easy to work with.

**Acceptance Criteria**

- [ ] Use mock data to generate raw data that is comparable to the actual data, which is supposed to be ~150 million rows and ~7GB.
- [ ] Research articles/studies of which databases would be ideal for handling this amount and type of data. The database should also be easy to work with in terms of pagination with filters.
- [ ] Once one or more suitable databases are found, try to set it up using the generated mock data.
- [ ] Add a summary of the findings with estimated hardware requirements and query response times.
- [ ] The changes are in alignment with the privacy policy

**Additional context**

Mock data should be added to this issue once it's ready.

**Comment by feiranl** [comment]
[MainData.zip](https://github.com/MetabolicAtlas/MetabolicAtlas/files/8824567/MainData.zip)
[supplOutput.zip](https://github.com/MetabolicAtlas/MetabolicAtlas/files/8824572/supplOutput.zip)
The MainData.zip contains the mock data for five organisms. We will have around 8000 this kind of files in the final version. The supplOutput file contains the cross reference Data for three 'species' : Compound Reaction and EC number.

**Comment by mihai-sysbio** [comment]
Here is more info about the dataset shared above by @feiranl.

As mentioned before, the data will be for many thousands of organisms.   Therefore, instead of having one long file on disk, the data can be set up in one file per organism. This is believed to be easier for now, which is why `MainData` contains multiple files with the same columns. These data should be used to populate the main table at the bottom of the individual pages.

**Comment by mihai-sysbio** [comment]
Regarding supplementary data, these are to be used to populate the first two small tables at the top of the individual pages.

**Comment by mihai-sysbio** [comment]
In line with the rest of the stack, it is envisioned for this database to be Dockerized.

**Comment by mihai-sysbio** [comment]
@inghylt: How often will the database be updated? Most likely around a couple of times per year.

**Comment by perjo** [comment]
### Short evaluation of storage options for enzyme database

**Size**: A db size of 9 GB with a table/collection with 150 million rows should not be a limiting factor nowadays. Many technologies should be able to work with this. 

**Structure of data**: This data seems to be structured and relational. It is given in a tsv-format with cross references (foreign keys). This points to using a relational database. 

**Read-only database**: A NoSQL database like MongoDB could make sense in this respect (optimized for reading, no need for transactions/consistency), but a relational db could absolutely do good enough. 

**Familiarity**: Using a technology we know about would be a plus. The DBMS I know we are using in other projects at NBIS are Neo4j and PostgreSQL. Neo4j is not suitable since this is not graph-like data, but PostgreSQL is a popular and proven product and SQL is a well-known standard. 

Based on this brief evaluation I would propose PostgreSQL for the enzyme database. At least I think it is a good first alternative to try. 

Discussions about handling large amounts of data in PostgreSQL: 

https://www.reddit.com/r/PostgreSQL/comments/mgnfn2/at_what_scale_will_postgresql_slow_down/
https://dba.stackexchange.com/questions/246003/which-db-for-1-table-with-100-million-rows-per-year
https://stackoverflow.com/questions/45629767/postgres-performance-for-a-table-with-more-than-billion-rows

**Comment by perjo** [comment]
I have imported the `mainData` files into a newly created PostgreSQL DB with no problem. The `supplOutput` files are a bit strange though. These files do not have the same number of files for all rows which one would expect from a TSV-file. This means PostgresSQL gives an error trying to importing these: 

```
# ERROR:  missing data for column "model_seed"
# CONTEXT:  COPY compounds, line 2454: "C03101	Coagulation Factor IX	"
```

(this row only contains two tabs while others contain up to nine) 

Now, I could of course work around this by applying a script but in order to keep the pipeline as simple as possible (less risk for errors) I would like to ask if it is possible to create data files with an equal number of fields for each line? @mihai-sysbio @feiranl

**Comment by nanjiangshu** [comment]
Great research @perjo! I think PostresSQL is a good option.

**Comment by perjo** [comment]
> @perjo Due to the lack of the cross-reference data, many compounds (and also reactions) indeed do not have the same number of fields as the others. To create the files with an equal number of fields for each line, I could fill in with "n.a." for those with missing data. Is this ok, or do you have any other suggestions?

@Yu-sysbio I think the best for us would be if the fields are blank if data is missing and there are an equal number of delimiters (tabs) for each row. If data is missing then a number of consecutive tabs is no problem. I.e. the row above would be

`C03101\tCoagulation Factor IX\t\t\t\t\t\t\t\t`

**Comment by perjo** [comment]
> Regarding the missing data, would this error still show if the DB fields allow for `NULL` entries?

Yes, error given even if column accepts `NULL`. See attached file for used sql. 

[import.txt](https://github.com/MetabolicAtlas/MetabolicAtlas/files/8851760/import.txt)

**Comment by e0** [comment]
> > Regarding the missing data, would this error still show if the DB fields allow for `NULL` entries?
> 
> Yes, error given even if column accepts `NULL`. See attached file for used sql.
> 
> [import.txt](https://github.com/MetabolicAtlas/MetabolicAtlas/files/8851760/import.txt)

Thanks! Definitely agree with you that it would be best if all the tabs at the correct places are included in the TSV files. Great work so far! While we finalize the mock files, I can start adding the DB to our project and start working with the full mock data generation.

**Comment by Yu-sysbio** [comment]
[supplOutput.zip](https://github.com/MetabolicAtlas/MetabolicAtlas/files/8853235/supplOutput.zip)
Please receive the updated files, in which I did as you @perjo suggested. Besides that, I included another cross reference source named "MetaNetX" for compound and reaction. Let me know if there are any issues.

**Comment by e0** [comment]
I wanted to test the performance of querying a larger table and used a modified version of [this script](https://github.com/MetabolicAtlas/MetabolicAtlas/blob/feat/enzyme-db-postgresql/pg/scripts/01-seed-mock-data.sql) to insert 10 million rows into the `enzymes` table. It's not the full ~150 million rows but hopefully this was close enough. This process took about 1 minute to complete.

Once this table was populated I tried some `select` queries and it seems quite fast. It appears that it gets progressively slower as more filters are added though. Here are some example results:
- `select * from enzymes where organism = 'O2' limit 50`: 2 ms
- `select * from enzymes where organism = 'O2' limit 50`: 712 ms
- `select * from enzymes where organism = 'O2' and compound = 'C5' and domain = 'D5' limit 50`: 1072 ms
- `select * from enzymes where organism = 'O2' and compound = 'C5' and domain = 'D5' and ko = 'K1' limit 50`: 751 ms, this seems faster again but might be due to only 10 rows are returned.

With this validated to some degree, I think we could continue working with using the data currently provided by the researchers. Thanks to @Yu-sysbio for providing the updated files! I will try to take a look at this now.

**Comment by mihai-sysbio** [comment]
Regarding performance when using filters, I think the more filter people use the more engaged they are, which makes them more willing to wait a few hundred ms more. If I would have to give a hard number, I think less than 2.5 s for multiple filters is good enough, especially for the MVP.
