### ISSUE TITLE
Deployment and database handling for EnzymeDB

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#1023]
As a developer, I want the EnzymeDB to be deployed together with the rest of the website, using the same commands, so that I don't have to do anything extra (manually).

Acceptance criteria:
- [x] do research if anything is deployed according to (security) best practice
- [x] update the resource allocation in Docker compose files
- [x] double check database field types
- [x] when importing data, would it be possible to have something less hard-coded, eg '/input_data/enzymes/*.txt' ?

Ideas:
- use hashes to see if the database has changed and needs redeployment
- use a flag as an indicator for redeployment

If there is no apparent way of doing this automatically, it is okay to do this kinda manually. At a minimum, these should be a way to deploy this.

**Comment by mihai-sysbio** [comment]
> For the remote system resources allocation, I assume that to start with we should assume that the total CPU and RAM remain the same right?

Indeed, we do not plan to add more resources.

> my local output for `docker stats`.

Please have a look in `prod` as well.

> taking half of the resource from `neo4j`

There are two types of resources allocated: `cpus` and `memory`. From what I see, `memory` is _over_-allocated for both `nginx` and `api`, so I propose to take a little bit from that as well. Regarding the `cpus` allocation, I guess most of it should come from `neo4j`, since many of the queries there will in the end be cached by `nginx`, but we can't expect that to be the case (to the same extent) for `pg`.

**Comment by e0** [comment]
Thanks for the answer about the system resources @mihai-sysbio , it's very helpful.

I have been preparing the automatic database creation and testing it on my local machine. I think this setup should be enough for the MVP and I would like some feedback and discussion to validate that thought. This is the matching commit if you are interested: https://github.com/MetabolicAtlas/MetabolicAtlas/commit/19edf218dec51979e408573729040e0c935bb974

This is how it currently works:

1. During the build stage, copy the input data as well as the `init.sql` script to the docker image.
2. During deployment (or locally `start-stack`), the postgres data is mounted and persisted to a local volume if it currently isn't. 
3. After deployment, postgres checks the mounted volume and if the database has not been initialized, the `init.sql` script would run to initialize the database and import the data.

The advantage of this setup are:
- The build stage only takes marginally longer compared to before. The extra time is for copying the input data, which should be done within a minute given solid internet connections.
- Since the data import happens after all the containers have started, the rest of the stack runs normally as the data is importing.
 
Since for both the build and run stages, it should not have significant impact on the rest of the stack, I think it's ok to have this as a part of the standard deployment process. Especially since the data import only happens unless the data volume has been removed.

The downside are
- if we do want to re-import, we would currently need to manually remove that data volume
- not sure if it was my machine slowing down, but the data import took significantly longer, ~45 min as opposed to ~10 min when importing the data "manually" using `ma-exec`.

Do we think that this is ok for the MVP? Any other feedback or questions is appreciated too.

**Comment by e0** [comment]
There has been some good progression following the previous message. I learned that the decreased performance with the mounted volume was most likely a macOS related problem/limitation. So I have reverted the local docker compose to not mount the volume. I also wanted to validate that the volume problem would not apply for linux systems such as our development server. So I have deployed to the dev server now and the data import with a mounted volume matches the local one (without mounted volume) and takes ~10min. Here is a screenshot of an EC page on the dev server along with a couple of response times for sorting the columns. As you can see it seems really fast!

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/423498/174344668-bb7ac869-a848-4f22-b5d7-3fe386c9ef2c.png">

I followed @mihai-sysbio's recommendations about how to [reallocate the resources](https://github.com/MetabolicAtlas/MetabolicAtlas/commit/c39dc7c895a223fa01c83094d4585d20faaa219a#diff-a70ffe88b408f9d7d827f488d6710304c47b6f6dace43cac4c61a376cc9717fa) before deploying. Following is the output for `docker --context met-dev stats` after deployment, data import, and a few test queries.

<img width="853" alt="image" src="https://user-images.githubusercontent.com/423498/174345083-489cc2c5-8cfe-414a-b82d-c6a9f247e275.png">

**Comment by e0** [comment]
A note about [the commit on schema changes](https://github.com/MetabolicAtlas/MetabolicAtlas/commit/92eef2cebdbec48eeae2573f2bad925a8a5dbbc4). Instances of `char` and `varchar` have been replace with `text` This is more flexible in both definition and storage cost. See the "Tip" section from https://www.postgresql.org/docs/current/datatype-character.html for more information.

In this commit, primary keys have also been added where appropriate. Primary keys get an index created automatically so those index creation lines have also been removed.
