### ISSUE TITLE
Incorrect formatting of chemical formulas in GEM browser and GotEnzymes 

### ISSUE THREAD

**Issue by MalinAhlberg** [MetabolicAtlas/MetabolicAtlas#1140]
**Describe the bug**

The chemical formulas are not always formatted correctly.

**Steps to reproduce**

See `/gotenzymes/reaction/R00073` and  `/explore/Human-GEM/gem-browser/reaction/MAR04223`. The `2` in `Prostaglandin G2` should not be `<sub>`ed.
See the discussion here https://github.com/MetabolicAtlas/MetabolicAtlas/pull/1139#discussion_r975111855

**Expected behavior**

Extract list of chemical formula from yaml file/db and create hard coded list of molecules.

**Screenshots**

![2022-09-20-133949_113x42_scrot.png](https://images.zenhubusercontent.com/5bd711b6c68d75301f4bd969/02059016-ef91-43b8-82dd-547c7c981819)

**Additional context**

Anything that does not follow this pattern can be ignored.

**Comment by nanjiangshu** [comment]
https://metabolicatlas.org/gotenzymes/reaction/R00078
equation![Screenshot 2022-11-17 at 14.04.59.png](https://images.zenhubusercontent.com/58ca67a651aa2c305778a403/4e7cfb99-f2ee-483b-9ed2-e67745f0454b)

should be 

Oxygen + 4 Fe<sup>2+</sup> + 4 H<sup>+</sup> ⇔ 4 Fe<sup>3+</sup> + 2 H<sub>2</sub>O

**Comment by nanjiangshu** [comment]
Extracting all molecules from the YAML file is not a good solution neither. For example, the atom `H` is also in the list of formulas from the YAML file, and therefore, the bad formatting of the reaction MAR03985 (https://metabolicatlas.org/explore/Fruitfly-GEM/gem-browser/reaction/MAR03985) can not be corrected by formatting only terms that match the list of formulas. ![Screenshot 2022-11-17 at 14.51.42.png](https://images.zenhubusercontent.com/58ca67a651aa2c305778a403/b612f66c-4118-4136-8169-355e859a2df7)

**Comment by nanjiangshu** [comment]
After checking the literature, I find it is fine to express prostaglandin H2 as prostaglandin H<sub>2</sub>, although H does not stand for hydrogen. This means Vitamin B6 can also be expressed as Vitamin B<sub>6</sub>. 
Therefore, the bug reported in this issue is not a problem.

However, two types of bad formatting still exist
1. ions with multiple charges, 
e.g. https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR01529
where Ca2+ is incorrectly formatted as Ca<sub>2</sub><sup>+</sup>

2. component name containing number but not a chemical formula, e.g. 
https://metabolicatlas.org/explore/Fruitfly-GEM/gem-browser/metabolite/MAM01782r
where emem2gacpail is incorrectly formatted as emem<sub>2</sub>gacpail

I think the first problem is more critical and it can be solved relatively easier by specifically checking if the atom is a metal atom. I haven't found any non metal atoms with multiple charges in the model file

The second problem is probably more tricky to solve.

**Comment by mihai-sysbio** [comment]
@nanjiangshu good call on problem 2. Let's not solve it, and remove any and all formatting on component names. This will also resolve the original issue, since `prostaglandin C2` is not formatted when it is a title on the Metabolite page https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02781e .

For problem 1, is there an easy/straightforward solution?

**Comment by e0** [comment]
> After checking the literature, I find it is fine to express prostaglandin H2 as prostaglandin H2, although H does not stand for hydrogen. This means Vitamin B6 can also be expressed as Vitamin B6. Therefore, the bug reported in this issue is not a problem.

Great research on this @nanjiangshu! Do you have any link to this literature that you mentioned?I was trying to read about this before too but wasn't sure how to look for it.

**Comment by nanjiangshu** [comment]
Hi @e0, if you search in Google scholar https://scholar.google.com/scholar?hl=sv&as_sdt=0%2C5&q=prostaglandin+H2&btnG=, you will find many articles using the form prostaglandin H<sub>2</sub>, but there are also articles using the raw form prostaglandin H2. In the PR I have chosen to use the raw form so that they are consistent with the title for metabolite name.
