### ISSUE TITLE
add new datasets for map overlay

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#1334]
**Please describe the feature**

As a user, I want the data overlay examples to be rich and diverse, so that I can explore the different ways of adding overlays onto the maps.

**Acceptance Criteria**

- [ ] add 1 dataset from @IVANDOMENZAIN
- [ ] Add documentation as to how the data-set was processed (in collaboration with Ivan)
- [ ] The web page documentation is updated accordingly
- [ ] Add a new entry under About -> Platform -> Citation -> Research-driven features for https://www.biorxiv.org/content/10.1101/2023.01.31.526512v1
- [ ] update the text in https://github.com/MetabolicAtlas/data-files/blob/main/DATA_OVERLAY.md#folder-structure-and-naming-conventions : the folders are now related to the overlay object type instead of data type (e.g. `gene` instead of `transcriptomics`)
- [ ] The changes are tested on multiple models and browsers
- [ ] Tests verifying the changes are added
- [ ] The API response is the same as before
- [ ] The changes do not affect the deployment
- [ ] The changes do not reduce the performance

**Additional context**

The first dataset is attached [here](https://app.zenhub.com/files/53664497/760cbf58-5302-453f-b7a4-4c5492e726a0/download) and should be stored in the `data-files` repository

**Comment by pdmnyberg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetAtlas-Roadmap-60d96b68da0fb10019d26deb/issues/MetabolicAtlas/MetabolicAtlas/1334?planning-poker) with Zenhub @pdmnyberg @Jessica-Sandler @jonandernovella @perjo

**Comment by mihai-sysbio** [comment]
> I am working under the assumption

Absolutely ✔️ 

The change that I am expecting is the scaling function. So essentially that would mean a new section (below, and conceptually similar to [the current description of scaling for data from HPA](https://github.com/MetabolicAtlas/data-files/blob/main/DATA_OVERLAY.md#scaling-of-gene-expression-levels-from-human-protein-atlas), but is already covered in the acceptance criteria. I hope Ivan will be providing the new description.

> I would need entries for ...

Let me loop in @IVANDOMENAIN and get back to you

**Comment by IVANDOMENZAIN** [comment]
Here is the description dataset `target_Matrix.tsv`:

For yeast-GEM, the gene targets from the study [Computational biology predicts metabolic engineering targets for increased production of 102 valuable chemicals in yeast](https://www.researchsquare.com/article/rs-2557470/v1) can be loaded by selecting one of the target chemical products in the drop down list. Once selected, the metabolic engineering strategy for increasing production of the chosen chemical will be displayed on the corresponding map, according to the color legend. Modified gene expression is represented using 4 discrete values:
- NA for genes with unmodified expression, color grey
- 0 for genes to be deleted, or Knocked-out, color white
- 0.4 for genes predicted to be modulated, knocked-down, color orange
- 1 for gene targets for overexpression, color red).

To clear the levels, select the `None` option in the drop down list or alternatively remove the corresponding card if levels from multiple data types are applied. Levels are available for both 2D and 3D Map Viewer. Gene engineering predictions were based on the (ecFactory method)[https://github.com/SysBioChalmers/ecFactory] and [ecYeastGEM](https://github.com/SysBioChalmers/ecModels). For more information regarding formulation of the method read the aforementioned [preprint article](https://www.researchsquare.com/article/rs-2557470/v1).

**Comment by mihai-sysbio** [comment]
We shouldn't wait for the second dataset - let's go ahead with the first one. The above description is for the About page documentation.

**Comment by pdmnyberg** [comment]
@mihai-sysbio @IVANDOMENZAIN So if I understand correctly the current data set describes 4 mutually exclusive `labels` (`[NA, KO, KD, OE]`)? So the actual values are more or less arbitrarily chosen? I am thinking of how to document process of getting the data ready for MetAtlas as in  `Add documentation as to how the data-set was processed (in collaboration with Ivan)` above.

In that case it would make sense to me to describe the process as assigning each `label` a color evenly distributed over `[0, 1]` and optionally include `NA`. Which in this case would result in the values `[NA, 0, 0.5, 1]` and in the general case `[NA, 1/N, 2/N, n/N, ..., N/N]` where `N` is the number of labels and `n` is the index of the associated label and `NA` is assigned to the label of index `0`.

I am guessing I might be wrong since you use `0.4` in the given data set.

**Comment by pdmnyberg** [comment]
@IVANDOMENZAIN do you have any suggestions on what to call the dataset in the list for `Select data source` in the `Data overlay` section . Since the available space is quite limited it would be nice to have a slightly less detailed title.

**Comment by IVANDOMENZAIN** [comment]
> @mihai-sysbio @IVANDOMENZAIN So if I understand correctly the current data set describes 4 mutually exclusive `labels` (`[NA, KO, KD, OE]`)? So the actual values are more or less arbitrarily chosen? I am thinking of how to document process of getting the data ready for MetAtlas as in `Add documentation as to how the data-set was processed (in collaboration with Ivan)` above.
> 
> In that case it would make sense to me to describe the process as assigning each `label` a value evenly distributed over `[0, 1]` and optionally include `NA`. Which in this case would result in the values `[NA, 0, 0.5, 1]` and in the general case `[NA, 0/N, 1/N, ..., (n-1)/N, ..., N/N]` where `N` is the number of labels -1 and `n` is the index of the associated label and `NA` is assigned to the label of index `0`.
> 
> I am guessing I might be wrong since you use `0.4` in the given data set.

Hi @pdmnyberg, You´re right, I also tried an even distribution of the discrete values across the 0-1 scale, however tested with different users and the feedback was that for some of them the color difference between 0.5 and 1 wasn't distinguishable enough, specially when overlaying data on a large map. Therefore, I arbitrarily chose 0.4 which was easier to distinguish to me and the colleagues that I consulted.

These results come from a constraint-based method that I developed, for each studied chemical product a list of gene targets is produced, which basically just indicates the gene IDs and the associated modification (Overexpression, knock-down and Knock-out). In order to generate the `tsv` matrix for metabolic atlas integration, I parsed each of these lists of results and created a matrix of values, having gene IDs (for all genes in yeastGEM) in the rows, and a column for each studied product. In this matrix, all genes are initially assigned with `NaN`, and then for each product, genes for KO are assigned with 0, KD targets with 0.4, and OE with 1, just for the sake of color differentiation.

**Comment by IVANDOMENZAIN** [comment]
> @IVANDOMENZAIN do you have any suggestions on what to call the dataset in the list for `Select data source` in the `Data overlay` section . Since the available space is quite limited it would be nice to have a slightly less detailed title.

What about `cell_factory_targets`? in case it is too long, then `gene_targets`is OK :)
