### ISSUE TITLE
make sure the gene page always shows related reactions

### ISSUE THREAD

**Issue by e0** [MetabolicAtlas/MetabolicAtlas#590]
As a user, I would like to be presented with a list of reactions when visiting the gene page, so that I can explore reactions that are associated with this gene.

Bug: For some genes, for example https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000000419, it shows 0 related reactions. This should not be possible since a gene should always be associated with at least one reaction to be considered as a part of a model. (Thanks to @pecholleyc for pointing this out.)

**Comment by mihai-sysbio** [comment]
However, on Metabolic Atlas we are to present the model as-is, so if genes that do not link to any reaction are included, we are to present those too. That being said, @pecholleyc is right - genes are added to a model because of their role in reactions.
By looking in the raw `yaml` file, one can see that this gene should be linked to at least 2 reactions.
