### ISSUE TITLE
Information on how to report bugs and vulnerabilities on the web-page

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#602]
_CII Best Practice badge: 
The project MUST provide a process for users to submit bug reports (e.g., using an issue tracker or a mailing list). (URL required)
The project MUST publish the process for reporting vulnerabilities on the project site. (URL required)_

As a user, I would like to be able to effortless report bugs and/or vulnerabilities, so that I don't have to waste time to find out how or ignore reporting out of laziness.

**Note**
1. This issue is mainly for adding user report portal on the frontend, the issue #601 will take are of the bug reporting related to the GitHub. 
2. This issue is also related to the private issue #601

**Comment by e0** [comment]
This issue was briefly discussed during backlog refinement today. We agree that it makes sense to add some information about this in `About` -> `Contact` for now. Previously the estimate received higher point votes because we discussed potentially more complicated solutions.

**Comment by mihai-sysbio** [comment]
I think this was resolved in #868, but @nanjiangshu should confirm.

**Comment by nanjiangshu** [comment]
Yes @mihai-sysbio. This issue is resolved with the addition of `bugs and vulnerabilities` text in the Contact page.

I have also updated the CII Best practice Badge 

See screenshot of changes

![Screenshot 2022-02-10 at 10.52.15.png](https://images.zenhubusercontent.com/58ca67a651aa2c305778a403/53449eed-53e2-4435-b356-3c1808ca7f72)![Screenshot 2022-02-10 at 10.55.32.png](https://images.zenhubusercontent.com/58ca67a651aa2c305778a403/1f6c2100-ee23-43dd-b5cc-c78587d385dd)
