### ISSUE TITLE
chemicalName not interpreted correctly for some metabolites 

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#629]
As a user, I would like chemical names for metabolites are interpreted by following [Hill system](https://www.wikidoc.org/index.php/Chemical_formula) for chemical formula.

Some examples to check:

/explore/Human-GEM/interaction-partners/m02043c (H2S2O3)
/explore/Human-GEM/interaction-partners/m02046c (HCO3-)

**Comment by mihai-sysbio** [comment]
Approach: try a general solution if it's easy enough, otherwise try to bugfix and create a separate issue.

Brainstorming:
- use a library
- rely on a database to store these string pre-formatted

**Comment by e0** [comment]
I'm not sure but to me it looks like some formulas are wrong in the data files? For example this one:

![image.png](https://images.zenhubusercontent.com/60992f121594d60ae1132a98/d1c5cdc2-916a-4929-921d-d92102bd3b66)

**Comment by e0** [comment]
I notice that the `chemicalName` function is used for the title in interaction partners, as opposed to `chemicalFormula` in other places (for example in the gem browser page). It looks like the formatting is inconsistent. For example for the metabolite `MAM02896c` these are the differences:

![image.png](https://images.zenhubusercontent.com/60992f121594d60ae1132a98/e874852e-eee7-42dd-bf65-a3d61af0d856)

![image.png](https://images.zenhubusercontent.com/60992f121594d60ae1132a98/645c06ad-8389-4d37-8758-1c58a457eeeb)

---

It looks like the `chemicalName` formula is only used in interaction partners. I'm inclined to modify so we only use `chemicalFormula` and remove the `chemicalName` as well as the `chemicalNameExternalLink` (this does not seemed to be used anywhere) functions. What do you think @mihai-sysbio? If we do that, I don't notice any problem with the `chemicalFormula` function itself as the problem seems to be from the data files as mentioned in the previous comment. If you notice any other examples where the formula is wrongly formatted by the `chemicalFormula` function please let me know. Otherwise I would consider this issue to be solved after the change to only use `chemicalFormula` and I suggest opening up issues in the model repos about the faulty formulae.

![image.png](https://images.zenhubusercontent.com/60992f121594d60ae1132a98/25dc211f-951c-4454-b12b-18de45372579)

![image.png](https://images.zenhubusercontent.com/60992f121594d60ae1132a98/b517f111-3ed2-4fac-9814-698d34bd8457)

**Comment by Hao-Chalmers** [comment]
@nanjiangshu sorry for cutting into this issue. Based on your description, it seems you are referring to `chemical formula, instead of `chemical name`. They are actually different things.

Please do let me know if I misunderstood the context.

**Comment by e0** [comment]
> It looks like the `chemicalName` formula is only used in interaction partners. I'm inclined to modify so we only use `chemicalFormula` and remove the `chemicalName` as well as the `chemicalNameExternalLink` (this does not seemed to be used anywhere) functions.

Follow up question about this. Do we want to show the name or formula for the interaction partners page title?

<h3 data-v-01f87706="" class="title is-3 m-0">Interaction Partners for C<sub>1</sub><sub>5</sub>H<sub>2</sub><sub>2</sub>O<sub>1</sub><sub>9</sub>P<sub>3</sub>R<sub>3</sub><sup>4-</sup></h3>

vs.

<h3 data-v-01f87706="" class="title is-3 m-0">Interaction Partners for RNA</h3>

---

<h3 data-v-01f87706="" class="title is-3 m-0">Interaction Partners for H<sub>3</sub>N</h3>

vs.

<h3 data-v-01f87706="" class="title is-3 m-0">Interaction Partners for NH3</h3>

---

I feel like for metabolite that have "proper" names, for example `RNA`, it looks better to show the name. For others, such as `NH3`, since that is basically just the formula it would look better to show the formatted formula. A suggestion is to see if the name contains a number in it, and if so we show the formatted formula, or else we show the name.

**Comment by e0** [comment]
> @nanjiangshu sorry for cutting into this issue. Based on your description, it seems you are referring to `chemical formula, instead of `chemical name`. They are actually different things.
> 
> Please do let me know if I misunderstood the context.

@Hao-Chalmers Thanks for the input. So chemical formula and chemical names are two different concepts? Can you please give me a couple examples of each? It would help me understand if we would need to consider both and how they should be presented.

**Comment by Hao-Chalmers** [comment]
@e0 you are right, chemical name and chemical formula are different concepts. For example, in GEMs two fields `metNames` and `metFormulas` are assigned for them, respectively. For a given chemical compound, the corresponding keys are `name` and `formula` in the yaml files.

**Comment by e0** [comment]
@Hao-Chalmers Thanks for the clarification. That makes sense, it sounds a bit misleading in the issue title and description because we do have a function called `chemicalName` (also discussed in this thread) and it wasn't clear exactly how or if that should be used. We originally thought that the two examples @nanjiangshu mentioned were due to the function `chemicalName` but just today found out that it may be a mistake in the model's data files as mentioned in [this comment](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/629#issuecomment-882700979).

**Comment by mihai-sysbio** [comment]
Thank you both for the discussion.

I'm thinking that a consistent naming scheme would have helped, so it sounds to me like `chemicalName` and `chemicalFormula` should be renamed so as to match the `yaml` fields, and perhaps also the fields in the database.

>  it may be a mistake in the model's data files

Excellent catch @e0. It seems there's nothing we should change on the formatting of these fields.

> Follow up question about this. Do we want to show the name or formula for the interaction partners page title?
> I feel like for metabolite that have "proper" names, for example RNA, it looks better to show the name. For others, such as NH3, since that is basically just the formula it would look better to show the formatted formula. A suggestion is to see if the name contains a number in it, and if so we show the formatted formula, or else we show the name.

Your suggestion sounds good @e0. I think this is consistent with what is shown on the Metabolite page titles in the GEM Browser.

In order to close this issue, @Hao-Chalmers here is a list of metabolites with names or formulae that might be worth revisiting as an issue in Human-GEM.

| MetaboliteID | Formula | Name |
-- | -- | --
MAM02043c | HO3S2 | H2S2O3
MAM02042c | HS | H2S
MAM02042s | HS | H2S
MAM02046c | CHO3 | HCO3-
MAM02046s | CHO3 | HCO3-
MAM02046m | CHO3 | HCO3-

**Comment by e0** [comment]
After discussion with @mihai-sysbio, it's established that the interaction partners page title should show `name` when available, or use `id` as a fall back (exact same as for genes and consistent with the gem browser pages). The `chemicalName` and `chemicalNameExternalLink` functions are then redundant and should be removed.
