### ISSUE TITLE
allow empty API responses

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#640]
In the case of requests with 0 responses, consider passing this response to the frontend instead of returning a 404 from the API. See original thread https://github.com/MetabolicAtlas/MetabolicAtlas/pull/544#discussion_r604740717 also related issue #1173

**Acceptance criteria**
- [ ] justification of keep the 404 or implementation of a switch to a 204, empty array (0 responses)
- [ ] no visual change are expected in the frontend (but how responses are dealt with might need updating) - this might require changes in the frontend code
- [ ] all tests pass

**Comment by mihai-sysbio** [comment]
I guess the conclusion are:
- 404 to be reserved for errors
- 200 to be used for non-empty responses

How do you plan on dealing with the empty responses: 200? 204?

**Comment by perjo** [comment]
# General thoughts about the API design 

The Metabolic Atlas API might be intended to never be consumed by any other program then the Metabolic Atlas frontend, still I believe there is much value in having a reusable API with clear separation of concerns. It appears to me as if this issue is concerned with how the API could be changed into being most easy to use from the use case of just the Metabolic Atlas frontend, which to me is not right starting point. We should work to make the API clean, consistent and intuitive instead. 

These are some thoughts on how to improve the API. Parts of this might be subjective and it is supposed to be a basis for further discussion. 

The API consist of URIs that identifies resources. In order to do this it uses [paths](https://www.rfc-editor.org/rfc/rfc3986#section-3.3) and [queries](https://www.rfc-editor.org/rfc/rfc3986#section-3.4). 

Paths are used to identify resources hierarchically, for example like `/customers/{customerId}/accounts/{accountId}` 

Query params are mostly used to filter or sort the resources identified by the path. 

There is no formal error in using query params for identification, but the above statements describe how the different kinds of parameters are generally used ([source 1](https://rapidapi.com/blog/api-glossary/parameters/query/), [source 2](https://www.abstractapi.com/api-glossary/query-parameters), [source 3](https://medium.com/@fullsour/when-should-you-use-path-variable-and-query-parameter-a346790e8a6d
)) 

The Metabolic Atlas API have several of resources identified as 

```
/compartments/{compartment-id}?model={model}
/genes/{gene-id}?model={model}
/metabolites/{metabolite-id}?model={model}
/reactions/{reaction-id}?model={model}
/subsystems/{subsystem-id}?model={model}
```
with the both the `id` and `model` parameters documented as required<sup>1</sup>, which I think is problematic.

`/compartments/{compartment-id}` should itself be sufficient to identify a compartment. Now there is also a required query param `model`, which could be interpreted as a filter of the compartments. I would make sense if this parameter was optional, to be able to return an unfiltered view of the compartments. 

While query params can be mandatory, this is sometimes considered as an anti-pattern (see https://apihandyman.io/what-s-the-problem-with-required-query-parameters/) 

To me an API constructed like  

```
/models/{model-id}/compartments/{compartment-id} 
/models/{model-id}/genes/{gene-id} 
/models/{model-id}/metabolites/{metabolite-id} 
/models/{model-id}/reactions/{reaction-id} 
/models/{model-id}/subsystem/{subsystem-id} 
```
would be more intuitive. With this design, a model is a collections of the compartments, genes, reactions, metabolites and subsystems for an organism which seem to conform with the definition of a GEM present of the web: 
("gene-protein-reaction associations for entire metabolic genes in an organism", "network-based tool that collect all known metabolic information of a biological system, including the genes, enzymes, reactions, associated gene-protein-reaction (GPR) rules, and metabolites"). To me this seems more semantically valid than seeing the model as a view of all full set of compartments, gene and metabolites.  

<sup>1</sup>It turns out the model parameter is currently not required as it is possible to make the request without error. 

# Regarding cases with no results 

## Current behaviour

`/compartments/{compartment-id}?model={model}` returns 404 if no compartment exists with this id 
`/genes/{gene-id}?model={model}` return 404 if no gene exists with this id 
`/metabolites/{metabolite-id}?model={model}` return 404 if no metabolite exists with this id 
`/reactions/{reaction-id}?model={model}` return 404 if no reaction exists with this id 
`/subsystems/{subsystem-id}?model={model}`  return 404 if no subsystem exists with this id 

**This is all fine and what you would expect**. The 404 (Not Found) status code indicates that the origin server did not find a current representation for the target resource ([source](https://httpwg.org/specs/rfc9110.html#status.404))

`/compartments/{compartment-id}?model={model}` returns 404 if model does not exist 
`/genes/{gene-id}?model={model}` returns 404 if model does not exist 
`/metabolites/{metabolite-id}?model={model}` returns 404 if model does not exist 
`/reactions/{reaction-id}?model={model}` returns 404 if model does not exist 
`/subsystems/{subsystem-id}?model={model}`  returns 404 if model does not exist 

**This is a bit strange**. If model is a query param then it is rather a filter than an id. If someone tries a request in which the filter is not defined then this should normally be a 400 BAD REQUEST rather than a 404 NOT FOUND. After all the compartment/gene/metabolite/reation/subsystem with this id did exist. 


`/compartments/{compartment-id}/related-reactions?model={model}` returns 200 with empty list if no compartment exists with this id 
`/genes/{gene-id}?model={model}` returns 200 with empty list if no gene exists with this id 
`/metabolites/{metabolite-id}?model={model}` returns 200 with empty list if no metabolite exists with this id 
`/reactions/{reaction-id}?model={model}` returns 200 with empty list if no reaction exists with this id  
`/subsystems/{subsystem-id}?model={model}`  returns 200 with empty list if no system exists with this id 

**This is also strange**. If compartment/gene/metabolite/reaction/subsystem does not exist then there should be a 404. 

`/compartments/{compartment-id}/related-reactions?model={model}` returns 200 with empty list if no compartment exists with this id 
`/genes/{gene-id}?model={model}` returns 200 with empty list if model does not exist  
`/metabolites/{metabolite-id}?model={model}` returns 200 with empty list if model does not exist 
`/reactions/{reaction-id}?model={model}` returns 200 with empty list if model does not exist 
`/subsystems/{subsystem-id}?model={model}`  returns 200 with empty list if model does not exist 

**This is also strange**, should return 400 BAD REQUEST (see above) 

# Proposed changes 

1.  `/compartments/{compartment-id}?model={model}` should be changed into `/models/{model-id}/compartments/{compartment-id}` and similarly 
2. These endpoints should return 404 if `id` or `model` does not exist. 
3. `related-reactions` and `related-metabolites` is redundant and should be replaced with just `reactions` and `metabolites`.

**Comment by mihai-sysbio** [comment]
> With this design, a model is a collections of the compartments, genes, reactions, metabolites and subsystems for an organism which seem to conform with the definition of a GEM present of the web.

Absolutely! Years ago, when the migration from Django to Neo4j was done, the decision was to slot the new database "in-place", which meant some technical debt was carried over. Most of that has been resolved, but as you can see, the API would need some touching up.

All the proposed changes are music to my years. However, they sound like an API revamp, which is a lot more than what is expected in the current issue. Therefore, I'm wondering if it would be possible to move the proposed changes to a new issue, and keep the work in the current issue to a minimum? Or would that mean duplicated work? Perhaps we should discuss this in our next session.

**Comment by perjo** [comment]
Moved to #1336. Closing this one.
