### ISSUE TITLE
API endpoint for 2D map thumbnails

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#677]
As a developer for an external resource (website for database/service), I want to show thumbnails of the SVG maps, so that I can enrich the user experience on the website I work on.
Desired: automate the generation of thumbnails (dynamic means less work in future deploys).
Optional: size of the thumbnail as a parameter (px).

Any feedback from HPA will result in a new issue.

**Comment by nanjiangshu** [comment]
Based on a search at npmjs.com with the keyword `thumbnail svg`, [sharp](https://www.npmjs.com/package/sharp) is one of the few javascript packages that support conversion of SVG to web-friendly image format such as png. Moreover, sharp is the most actively maintained, with 110 releases and the latest release just 20 days ago. In addition, resizing of images for sharp is typically 4-5 times faster than using the quickest mageMagick and GraphicsMagick settings due to its use of libvips. Therefore, I think `sharp` is a good solution for dynamic creation of thumbnails from the 2D SVG maps.

**Comment by mihai-sysbio** [comment]
Sounds excellent @nanjiangshu!
