### ISSUE TITLE
3D Map Viewer does not jump to the map region after selecting a map on mobile

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#678]
As a user, I would like the 3D map viewer will be re-focused at the map region after selecting a map on a mobile device, exactly as for the 2D Map viewer. 

Attached please find a video recording of the described problem. 
https://images.zenhubusercontent.com/53664497/32d49793-ce03-41bb-939e-53ade5ead459/svid_20210827_225805_1.mp4

It should be one or two lines of code change. The same problem has been solved for the 2D map viewers.

**Comment by mihai-sysbio** [comment]
I remember @shan-chalmers implemented an equivalent fix for the 2D maps. Perhaps that implementation can be generalized to include both 2D and 3D viewers.

**Comment by MalinAhlberg** [comment]
Nice work!
Potential issues I found:
- If I scroll back down and select the map that I'm already at (which at least happens to unfocused users like me...), I don't get back to the top of the page.
- I get a module error saying that `vuex import should occur before import of @/helpers/utils at src/components/explorer/gemBrowser/Tile.vue:64`. This might be some local, unwanted code check though, since you guys seem to have no problem with it.
