### ISSUE TITLE
Not possible to switch to 3D maps

### ISSUE THREAD

**Issue by MalinAhlberg** [MetabolicAtlas/MetabolicAtlas#756]
**Describe the bug**
When visiting the map viewer, it's not possible to switch to 3D if there are no 2D maps.

**To reproduce**
- Navigate to Explore
- Select Zebrafish and Map Viewer
- Try to switch to 3D

**Expected behavior**
3D should be the default if there are no 2D maps. The 2D map button should be disabled.

**Additional context**
See comments [here](https://github.com/MetabolicAtlas/MetabolicAtlas/pull/746#issuecomment-963329101).

**Comment by inghylt** [comment]
Another related issue that probably makes sense to fix here as well

"When visiting /explore/Fruitfly-GEM/map-viewer/phenylalanine_tyrosine_and_tryptophan_biosynthesisxxx?dim=2d, the message says "probably there is a typo in the map identifier in the URL. Use the list of maps to find other maps". However, since the 2D maps for phenylalanine_tyrosine_and_tryptophan_biosynthesisxxx does not exist, all entries on the map listing table are disabled"

https://github.com/MetabolicAtlas/MetabolicAtlas/pull/746#pullrequestreview-802341475

**Comment by inghylt** [comment]
This issue fix should also be the case for https://metabolicatlas.org/gems/repository and not only Explore

**Comment by e0** [comment]
> Another related issue that probably makes sense to fix here as well
> 
> "When visiting /explore/Fruitfly-GEM/map-viewer/phenylalanine_tyrosine_and_tryptophan_biosynthesisxxx?dim=2d, the message says "probably there is a typo in the map identifier in the URL. Use the list of maps to find other maps". However, since the 2D maps for phenylalanine_tyrosine_and_tryptophan_biosynthesisxxx does not exist, all entries on the map listing table are disabled". From comment [#746 (review)](https://github.com/MetabolicAtlas/MetabolicAtlas/pull/746#pullrequestreview-802341475)

During backlog refinement, it's decided that we should also try to fix this bug if it looks like a simple fix since they are very related. If it turns out that the fix is too different and would require longer time, please create a new issue for it instead.
