### ISSUE TITLE
research testing framework

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#779]
**Please describe the feature**

As a developer, I want to explore and evaluate some testing frameworks so that I can start the work of incorporating test frameworks to the project.

**Describe the solution you would like**

This issue should conclude with one or more issues for adding testing frameworks to the project based on the findings of this issue. #780 is a related issue that could be fleshed out with more details.

The types of testing that would be nice to included are:
- API testing: Good for making sure that the data is not modified (unless intended) when working on new features
- unit testing: Good for making sure that an individual function (for example formatting chemical reactions) work for a series of test cases. Would be nice to have the same framework that works both for the frontend and backend.
- UI testing?: Good for making sure that the UI is working as intended. For example, "When I go to the random components page, I should see one compartment, two reactions, etc..." Keep in mind that these tests usually take longer to write and the effort/reward ratio may not be as good as the other types of testing. It still may be worth exploring during this issue though.

**Additional context**

As with most research issues, it may require more discussion to get everyone on the same page. If you have any suggestions for changing the scope of the issue, or have any questions, please feel free to add a comment.

**Comment by inghylt** [comment]
@e0 @nanjiangshu @MalinAhlberg 

As I see it, we have two main categories of testing that we want to perform

- Unit and integration tests

- E2E testing

For Unit and integration tests, it seems that Mocha and Jest are the most popular and relevant ones
I base this on usage stats in https://2020.stateofjs.com/en-US/technologies/testing/, recommendations in https://vuejs.org/v2/guide/testing.html but also general lists such as https://www.browserstack.com/guide/top-javascript-testing-frameworks where Jest and Mocha are always in the top. They both support node.js and vue.js. 

I think it makes sense to go with Jest since Mocha is highly extensible and relies of extra libraries, which can introduce configuration complexity and increase maintenance work [source](https://blog.logrocket.com/the-best-unit-testing-frameworks-for-node-js/). Feels like it is nice to have a framework with minimal work. Jest also support the most test types in this article https://medium.com/welldone-software/an-overview-of-javascript-testing-7ce7298b9870. Also, feels like it makes sense to use the most popular framework that scores the highest on all categories in https://2020.stateofjs.com/en-US/technologies/testing/
In addition, I have tried out Jest before and thought it was easy to work with.

For E2E testing, https://vuejs.org/v2/guide/testing.html recommends, Cypress.io, Nightwatch.js, Puppeteer and TestCafe.  Linus, a SciLifeLab dev, recommends Nightwatch.js, and Dan, a talented dev former working at NBIS, recommends Playwright. All of these are also mentioned in https://medium.com/welldone-software/an-overview-of-javascript-testing-7ce7298b9870. Not sure if we should go more into detail on E2E testing now but to let it be a future issue? Since it is mainly data verification we prioritize in this first testing stage.

Let me know what you think about this and if you are missing anything

**Comment by e0** [comment]
Really good work here @inghylt!

I was intrigued by [uvu](https://github.com/lukeed/uvu) for unit testing but it's so new so I fully support using jest for our project since it's so widely used and has good docs/resources if we run into any problems.

I took a quick look at the E2E names and find playwright quite intriguing. The syntax being very similar to jest is a huge plus imo. Of the names you mentioned I have worked the most with puppeteer but I think that's more focused on browser automation.

It would be good to look a bit into how well these would run inside Docker as well. For E2E we technically don't need to have it run in Docker but it could be nice to have a reliable containerized setup that can test multiple browsers simultaneously.

**Comment by mihai-sysbio** [comment]
@inghylt very nice and well docummented summary 🌟 
I'd like to emphasize @e0's last point: it would be nice to know how easy these tools would be to set up with GH Actions. Not that we have to get there in one go, but it would be great to get there eventually. I remember it was a bit of a headache to get Cypress to work with Docker - I'm not even sure we got it to work.

**Comment by inghylt** [comment]
I'm experimenting on how to use jest . I've had **struggles** with just making jest run with our normal import statements. This branch contains progresses made https://github.com/MetabolicAtlas/MetabolicAtlas/tree/test/research-test-frameworks. At first I wanted a solution that did not require babel but then I realized we already had a babel.config.js file + seemed to be the most legit thing to use with jest so went with that. Using babel and following [this comment](https://github.com/facebook/jest/issues/9395#issuecomment-583799300) solved the problems I had, god bless.

Moving forward I will experiment a bit more with GH actions

**Comment by MalinAhlberg** [comment]
Nice work, @inghylt :v:  !
I'm not familiar with any of the testing frameworks, but it seems you have researched them well enough for me to trust your conclusions :). Based on some quick reading, I think Jest looks good. All of the E2E frameworks seems fine too. Nightwatch beeing "older and more time-proven" does not sound so bad. But I'm really up for all of them!

I also think it makes much sense to divide the implementation of this into different issues.

**Comment by inghylt** [comment]
I played around a bit more with an api test, was not able not make it work. Since this issue was mainly related to research I'm thinking it is worth to spend time on it when we work with #780

Have a look at https://github.com/MetabolicAtlas/MetabolicAtlas/pull/798 to see a small unit test and how it runs with the help of GitHub actions

My suggestion is to leave that PR in draft mode until we start working with #780 and consider this issue to be done. Is that a good suggestion?

**Comment by mihai-sysbio** [comment]
It'd be very nice to have a clear summary here to be "reviewed" that would constitute the bases of the implementation issue. If there is stuff that won't be implemented immediately, I'm in support of having several "expand testing" cards.

**Comment by inghylt** [comment]
- As written https://github.com/MetabolicAtlas/MetabolicAtlas/issues/779#issuecomment-984380619, Jest is the suggested framework to use for unit and integration testing since it is widely used, does not require configuration of external libraries and has a lot of functionality for different types of test
- #780 shows a Jest unit test in combination with GitHub actions, a small demo that it should work within our workflow
- Experiments were made to make an api test as well in Jest, but the messiness with different types of js import  (see example thread [here](https://github.com/facebook/jest/issues/9395#issuecomment-583799300)) which was fixed for the unit test resurfaced, possibly because I experimented with `axios` and not `supertest` for HTTP calls which seems to be mainstream together with Jest. Also, we might want to use the code available in `MetabolicAtlas/frontend/src/api` instead. As discussed at standup, this is a research issue and not too much time should be spent on actually implementing the tests. Thus, no more time was spent on this. Jest is such a widely used framework so I'm confident we will be able to implement the tests we would like in issues such as #780
- As written https://github.com/MetabolicAtlas/MetabolicAtlas/issues/779#issuecomment-984380619, no specific framework is suggested for E2E testing since it is mainly data verification we prioritize in this first testing stage and E2E tests are not required for this. I believe it is wise to dive deeper into E2E frameworks once we are at a more mature stage of data verification. But https://github.com/MetabolicAtlas/MetabolicAtlas/issues/779#issuecomment-984380619 lists some available frameworks and recommendations which we can use in the future

**Comment by nanjiangshu** [comment]
Great work and nice discussion @inghylt. I have not used any of the tools mentioned here but based on the satisfaction chart as well as the activities, I guess Jest will be a good choice. I will try out Jest and other tools and then might come with more feedback 😃

**Comment by mihai-sysbio** [comment]
The summary presents robust conclusions @inghylt 🌟 
If I would have to choose between integration and E2E testing, I would keep the latter. The impression I have is that for now the focus will be on unit testing, and that there is no hard conclusion for E2E testing.

**Comment by nanjiangshu** [comment]
I tried Jest testing locally and it worked like a charm. However, in order to do the data verification testing with the API that accesses the neo4j database, we may need to run the test with docker integration. There are examples of such tests, although I did not succeed with a quick try. Nevertheless, for this research issue, I would say @inghylt has done a very good exploratory work and a nice conclusion.
