### ISSUE TITLE
"See reactions from all compartments" button has no effect

### ISSUE THREAD

**Issue by JonathanRob** [MetabolicAtlas/MetabolicAtlas#832]
**Describe the bug**
On metabolite pages in the GEM browser, selecting the `See reactions from all compartments` button doesn't seem to do anything.

For example, on the page for [`cholesterol[c]`](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01450c), 25 reactions are shown to involve that metabolite. When `See reactions from all compartments` is selected, no additional reactions appear (still 25). However, if one looks at the page for [`cholesterol[l]`](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01450l), 71 reactions are shown, suggesting that more reactions for `cholesterol` did exist.

**Steps to reproduce**
On the [`cholesterol[c]`](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01450c) page, click on `See reactions from all compartments`.

**Expected behavior**
On a metabolite page, clicking the `See reactions from all compartments` button should show reactions involving any compartment form of that metabolite. In the specific example provided, since there are 71 reactions involving the `cholesterol[l]` metabolite, then clicking the `See reactions from all compartments` button on the `cholesterol[c]` page should increase the number of reactions shown to more than 71 (likely above 100).

**Comment by mihai-sysbio** [comment]
Thanks for the bug report @JonathanRob . It looks like we might not have time for it in this sprint, but it's in our _Immediate_ list.

**Comment by nanjiangshu** [comment]
It worked before, so one might start with `git bisect`

**Comment by inghylt** [comment]
Some research:
The functionality in question is provided by `frontend/src/components/explorer/gemBrowser/ReactionTable.vue`. `Gene.vue`, `Metabolite.vue` and `Subsystem.vue` all use this component but only `Metabolite.vue` enable this functionality by using prop `:relatedMetCount`. When clicking the button, this code will be called:

```const payload = {
  model: this.model.database_name,
  id: this.sourceName,
  allCompartments: this.expandAllCompartment,
};
await this.$store.dispatch(`reactions/getRelatedReactionsFor${this.type[0].toUpperCase()}${this.type.slice(1)}`, payload);
```

However, `getRelatedReactionsForMetabolite` in `frontend/src/store/modules/reactions.js` does not make use of the argument  `allCompartments`, as this was removed when the db was changed to neo4j, see [this commit](https://github.com/MetabolicAtlas/MetabolicAtlas/commit/432a67ef5db7f2b1bc40295ee1c3225f392e3da2#diff-82dd33b8394d71bf6afe233bd26c56b8aaee54528d8ddcc210fb9f4ec7296a73), and seems like that has been the case ever since

**Comment by e0** [comment]
This was quite straightforward to fix so adjusted story points from 3 to 2.
