### ISSUE TITLE
Refactor: avoid using <br> tags when possible and use CSS instead

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#873]
**Please describe the feature**

As a developer,  I want to avoid using `<br>` tags as much as possible to improve the visualization stability. (22 occurrences in 4 files)
Sometimes these appear in json files.

**Describe the solution you would like**

Use CSS instead

**Additional context**

Related comment: https://github.com/MetabolicAtlas/MetabolicAtlas/pull/866#pullrequestreview-876063884
Bulma has margin and padding classes.

**Comment by e0** [comment]
Looking into this issue now and the inconsistencies with why the margin and padding helpers in Bulma don't seem to behave consistently, for example `pt-6` does not give the same vertical spacing as `mt-6` in [this instance](https://github.com/MetabolicAtlas/MetabolicAtlas/pull/974/files#diff-1507d3a6d2defa69d6126504cb746cc302b08969518a5394d4bf0df1ab6887cbR66). This is due to the fact that the `columns` class has a top margin of `-0.75rem` and the `column` class has a padding of `0.75rem`.

For cases like this, it would be more semantic to use margins instead of paddings as the goal is to [add extra space around en element](https://developer.mozilla.org/en-US/docs/Web/CSS/margin#description). I think Bulma's implementation of `columns` and `column` is problematic as it leads to situations like this. Having said that, Bulma is already used heavily in the project and I think it would be more productive to work within Bulma's design decisions as opposed to using custom CSS to fix this. The main argument for this is that even with custom CSS, it would still not be straightforward why a margin of `2.25rem` is used for an effective vertical spacing of `1.5rem`. If anyone has an counter arguments, please let me know and I would be happy to reconsider this.
