### ISSUE TITLE
Improve scoring

### ISSUE THREAD

**Issue by MalinAhlberg** [MetabolicAtlas/MetabolicAtlas#896]
**Please describe the feature**

As a user I want the scoring from neo4j to be improved so that I'm always presented with the most relevant search result.

**Describe the solution you would like**

- When searching for `3(R)-hydroxy-(2S,6R,10)-trimethyl-hendecanoyl-CoA` you should get `MAM00685p` as the top result (currently gets score 0).
- ~When searching for `fatty` the top result should not be the gene `FASTK` as top result.~ Moved to new issue #978.

**Acceptance Criteria**
- [ ] Add tests related to search, covering all compartments and more than 1 model

**Additional context**

Related:
https://github.com/MetabolicAtlas/MetabolicAtlas/pull/886
https://github.com/MetabolicAtlas/MetabolicAtlas/pull/887

**Comment by inghylt** [comment]
I've done some research this morning and I now know why this still is an issue despite #937

If you search for example `3(R)-hydroxy-(2S,6R,10)-trimethyl-hendecanoyl`, `MAM00685p` will not be part of the result returned at [this line](https://github.com/MetabolicAtlas/MetabolicAtlas/blob/1e665d2373d59ec92038bc324494608cdeba07b3/api/src/neo4j/queries/search/modelSearch.js#L202), but the object

`{
     score: 14.249983787536621,
     id: '3_r_hydroxy_2s_6r_10_trimethyl_hendecanoyl_coa',
     labels: [ 'Metabolite', 'HumanGem' ]
 },`
 
while the obj used in [this row](https://github.com/MetabolicAtlas/MetabolicAtlas/blob/1e665d2373d59ec92038bc324494608cdeba07b3/api/src/neo4j/queries/search/modelSearch.js#L259) will look like

`{
   name: '3(R)-hydroxy-(2S,6R,10)-trimethyl-hendecanoyl-CoA',
   compartment: 'Peroxisome',
   id: 'MAM00685p'
}`

So [this line](https://github.com/MetabolicAtlas/MetabolicAtlas/blob/1e665d2373d59ec92038bc324494608cdeba07b3/api/src/neo4j/queries/search/modelSearch.js#L261) will result in a score of 0, since  id  `MAM00685p` is not part of the result returned at [line](https://github.com/MetabolicAtlas/MetabolicAtlas/blob/1e665d2373d59ec92038bc324494608cdeba07b3/api/src/neo4j/queries/search/modelSearch.js#L202). We need to link the first result with the second so we get the true score.
