### ISSUE TITLE
Research UX for new gem repository

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#929]
**Please describe the feature**

As a developer, I want UX drawings for the new GEM repository so that I know what should be implemented.

**Acceptance Criteria**

- [ ] UX drawing(s) on how the new GEM repository should look like

**Additional context**
Background information for this issue can be found in https://github.com/MetabolicAtlas/private-issues/issues/127. As concluded there, this issue should focus on creating UX drawings on how the integrated models (category A) should be arranged in the a layout. The main focus of this new layout is to
- allow users to see the history, i.e. previous versions, of the models. For example, Human GEM have [40 releases](https://github.com/SysBioChalmers/Human-GEM/releases) but for users to know about this today they have to visit their github page
- allow users to see how models might have branched out from a previous model. This is not the case for all models, e.g. Human-GEM and Yeast-GEM will probably be linear, while several of the other models origin from a specific version of Human-GEM. This relationship should be clear.
- allow users to see additional information/analysis of the models, for example if they conform to quality standards

It is not a requirement to include it in this issue, but displaying additional information about the model versions such as information available [here](https://github.com/MetabolicAtlas/standard-GEM-validation) (category C), should at least be kept in mind when doing the UX drawings. This information might be shown as some kind of popup when you click or hover a node.

One should also keep in mind that the long term goal is for A) B) C) and D) to all have this kind of graphics.

**Comment by inghylt** [comment]
- How to handle a lot of versions?
- Should we separate major minor patch, e.g. through the size/form on the node?
- Click on node to get to the release?

**Comment by mihai-sysbio** [comment]
> * How to handle a lot of versions?

While an animation that collapses the nodes would be nice, I think a toggle (that shows all versions by default) would be enough.

>     * Should we separate major minor patch, e.g. through the size/form on the node?

Interesting idea, if it's easy enough. Perhaps something that can also be done later on.

>     * Click on node to get to the release?

Even more than that - click a node should bring up more detailed info: buttons to GitHub, standard-GEM assessment, etc.

>     * Should we visualize when a release is made, i.e. clear timeline?
> 
>     * Should we include pre release?

**Comment by inghylt** [comment]
- https://sourceforge.net/projects/yeast/files/ The first release of the yeast gem was 2012, followed by multiple releases until it was moved to GitHub 2018. Should we show the activity before 2018?
- Should we show all types of versions or dismiss patch versions?
- What would we toggle through show all? Would only the latest releases be shown or some kind of year limit?
- We are only able to show map viewer and gem browser for the latest versions right?
- Are we able to get reaction, metabolites etc. count on all versions or only the latest?
- Should we differentiate the nodes based on if they pass the standard-GEM assessment or not, e.g. through color?

**Comment by inghylt** [comment]
https://js.cytoscape.org/demos/colajs-graph/
Inspiration for detailed information when clicking on node

**Comment by e0** [comment]
@inghylt , @MalinAhlberg , and I had a meeting yesterday to discuss more about this issue and we decided to each work on some sketches. We just had a follow-up meeting this morning. This was a really fun activity and a great way to collect ideas!

Here is my sketch and follow up notes. Please ignore the questions included in the sketch as they have already been addressed elsewhere. Things I would change about this sketch after the meeting are:

- Do not show the modal immediately after clicking a node. @inghylt had a good cytoscape example of a little info dropdown instead. If we want to we could include a "More information" link in this dropdown that displays a modal.
- Nice to still include the list of integrated GEMs as in @MalinAhlberg's mockup. It would be nice if we can also redesign it a bit, perhaps even to a tabular format that takes up less screen space and attention.
- I think both @inghylt and @MalinAhlberg and different sized nodes to represent major/version/patch releases, which is really nice visual guide. It would be nice to have different colors for each GEM/branch as well.

<img width="629" alt="image" src="https://user-images.githubusercontent.com/423498/160789036-abffabaa-5a58-49db-86d2-09de8f2c718b.png">

**Comment by MalinAhlberg** [comment]
Here's my sketch. The idea is to keep bigger boxes / items for the latest versions of the integrated versions, and visualize other versions as bubbles.

Things I didn't do, but wish I had:
- A timeline (as in @inghylt 's and @e0 's versions) 
- list patches under the minor/major nodes (as in @e0 's version)
- smaller dropdown when clicking nodes (as in @inghylt 's version)

![v2.png](https://images.zenhubusercontent.com/5bd711b6c68d75301f4bd969/2a6c08db-825d-48e4-a9b3-df512f2448b5)

**Comment by mihai-sysbio** [comment]
>     * https://sourceforge.net/projects/yeast/files/ The first release of the yeast gem was 2012, followed by multiple releases until it was moved to GitHub 2018. Should we show the activity before 2018?

For now we can stick to the the releases that exist on GitHub. Everything that is not on GitHub has a much lower priority ([data set D](https://github.com/MetabolicAtlas/private-issues/issues/127)).
 
>     * Should we show all types of versions or dismiss patch versions?

For a first version I think we can dismiss patch versions but keep the door open for an extension (if it becomes needed).

>     * What would we toggle through show all? Would only the latest releases be shown or some kind of year limit?

Good question! I was imagining this would fold all minor releases and only show the major ones (or at least 1 release).

>     * We are only able to show map viewer and gem browser for the latest versions right?

Yes please.

>     * Are we able to get reaction, metabolites etc. count on all versions or only the latest?

Only on latest, since this is dynamically computed (@nanjiangshu knows more how this is done).

>     * Should we differentiate the nodes based on if they pass the standard-GEM assessment or not, e.g. through color?

It is very important to differentiate, but there is no restriction on how this is done (color or otherwise). Also, very likely that standard-GEM will not be the only reason for differentiation.

**Comment by nanjiangshu** [comment]
Thanks for the great research you have done and I like the sketches you made. 
I really like the idea of using different bubble sizes and colors for major/minor and quality of releases. 
Below I list some of my thoughts

1. I think we should still keep the current list for Integrated models but maybe in a more compact design. I guess the integrated models will still be the most frequently used endpoint when the users want to explorer a GEM. The tree view of GEM history will give the user an dynamic perspective of how GEMs at MetAtlas evolve, however, from a practical point of view, some statistical data/graphs are more likely to be cited in publications.

I would suggest we keep the current integrated GEMs list as a section and the GEM history in a new section  


2. Displaying the names of GEMs besides every node might be a bit too much. We can have several options.
    - Use different shapes for different GEMs and the names are annotated in the legend 
    - Use the same shape for GEMS and mark the names of GEMs at the root and every fork
    - Use different shapes for different GEMs and mark the names of GEMs at the root and every fork
    
     I'm open for other better solutions 

3. The number of counts are calculated dynamically based on the neo4j database. For older version of GEMs, they can not be calculated in this way. Since the older versions will not be changed, I think we can calculate them at once based on the YAML files and store them in a JSON file.

**Comment by mihai-sysbio** [comment]
> 3\. The number of counts are calculated dynamically based on the neo4j database. For older version of GEMs, they can not be calculated in this way. Since the older versions will not be changed, I think we can calculate them at once based on the YAML files and store them in a JSON file.

Since this requires manual work, another option would be to make a note about these counts to be added via dataset D (in the future), and only display counts on the last integrated GEM, for which the counts are obtained automatically.

**Comment by inghylt** [comment]
[Figma drawings](https://www.figma.com/file/0KIii23icCOgACJiodqbqv/History-of-GEM%3As?node-id=0%3A1)
