### ISSUE TITLE
Decide data format for the new GEMs repository

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#950]
**Please describe the feature**

As a developer, I want a proper data format to store data that will be used for the new GEMs repository and also a place to store the data (a folder? in the `data-files` repository).

The data is including but not limited to
* Release data (version, date, link to github)
* References to the publication
* Counts of genes, metabolites and reactions (compulsory only for the "latest")
* Quality standards based on standard GEMs 

**Acceptance Criteria**

- [ ] summary of proposed format documented in the Dev docs (wiki)

**Additional context**

The data format should take the future integration of data types other than integrated models (see [private #127](https://app.zenhub.com/workspaces/metatlas-sprint-607745622d49260019ce115a/issues/metabolicatlas/private-issues/127) for details) into account.

**Comment by inghylt** [comment]
This issue stems from #929

**Comment by inghylt** [comment]
### Location
Since we have all the data related to the models in the repository `data-files`, I think it makes sense to keep it that way.

We currently have a folder named [integrated-models](https://github.com/MetabolicAtlas/data-files/tree/504ae593d4bbe0694214ba417b160abd92f34713/integrated-models). I would suggest we use this folder to store the metadata related to the gem repository for the integrated models. I would suggest something like this:
 
```
data-files/integrated-models/gemRepository/
   releaseData.filetype
   countData.filetype
   validationData.filetype
```
I think it make sense to keep the different types of data separated into different files for separation of concern. 

### FiIe format
I think the json file format would make sense since it is an easy way to store key val relationships. I think the json files could have this kind of format:

```
{
   'Yeast-GEM': { ... }
   'Rat-GEM' : { ... }
...
}
```
Note though that this differs from how things are arranged in for example [integratedModels.json](https://github.com/MetabolicAtlas/data-files/blob/504ae593d4bbe0694214ba417b160abd92f34713/integrated-models/integratedModels.json), where model objects are stored in an array. I think the file layout depends on how we want to create the graph, e.g. iterating objects in one file or using multiple for different types of data.

### Other gem repository categories
If we in the future want to add metadata related to category [B)](https://github.com/MetabolicAtlas/private-issues/issues/127), i.e. models listed in the GEM repository, I think the gem repository metadata could be placed in their respective folder, for example:
`data-files/repository/bacteria_models/gemRepository`
`data-files/repository/fungi_models/gemRepository`

We currently don't have data related to [D)](https://github.com/MetabolicAtlas/private-issues/issues/127) (right?), so it's hard to give an example, but I think we should be able to use a similar structure for those models as well.

### Additional comment
This is only a suggestion so please come with feedback and other suggestions

**Comment by inghylt** [comment]
@e0 @MalinAhlberg @mihai-sysbio @nanjiangshu Please read this and give feedback/other suggestions

**Comment by nanjiangshu** [comment]
Great research for the data format @inghylt! I think it makes sense to store the data files at `data-files` repo and inside its corresponding GEMs folder, that is, for the integrated GEMs, under `data-files/integrated-models/<GEM-NAME>`. For other GEMs, I think `data-files/non-integrated-models/<GEM-NAME>` might be a better place. 

I'm not quite convinced to separate files into different JSON files unless there are some (future) data which can not be stored in the data structure, that is, all data are grouped by releases in the first order. 

I think the outline of the data structure as 
```
{
   'Yeast-GEM': { ... }
   'Rat-GEM' : { ... }
...
}
``` 
looks very good.

**Comment by e0** [comment]
Thanks for the proposal @inghylt!

I agree with @nanjiangshu and think it would be nice if we can have everything in a single JSON file. In addition to the question about how relationships are handled, it would also be nice to have an example of how the data should look like for a specific version of a model. For example, for version `1.0` of `Human-GEM`, which fields (and types for each field) should be included?

Understanding these points would make it clearer for us to begin the data collection and creating mock data for the frontend implementation. Knowing the full structure of the JSON file would also help decide where the location of the file should be. For example, if it turns out that we would like to included some UI related fields (different colors for different models for example), then maybe there would be an argument for placing this file in the main project repo under `./frontend`.

**Comment by mihai-sysbio** [comment]
> data related to [D)](https://github.com/MetabolicAtlas/private-issues/issues/127)

Here is the link to the data for D) https://github.com/MetabolicAtlas/tree-of-GEMs/blob/aee1281814329ca3427a0060f666139efb986c29/editDataset/dataset.json

**Comment by MalinAhlberg** [comment]
Good research!

I haven't got much more to add, other than what has already be mentioned.

One thing I'm not quite clear about is how to model the versions, ie the nodes of the UI graph. A list of objects? Would it make sense to have id:s for each node? So that they could all keep reference to their parent (defaulting the previous version), that could be (manually?) set to a node of a different file/species?

**Comment by inghylt** [comment]
Notes from standup:
- Might make sense to have everything in one file and not under each gem to make it easier to display branch relationships
- Good with full example so we can see what data we need (for example if there is need for UI "data")
- ID, probably needed? Will see once we have full example

Todo:
- Create full example

**Comment by inghylt** [comment]
@MalinAhlberg @mihai-sysbio @nanjiangshu @shan-chalmers 
After the discussions in the comments and live after standup today, here is a new suggestion:

data-files/integrated-models/Human-GEM/gemRepository.json
```
{'Human-GEM': [
   { 'id': 'Human-GEM-1.0.0'
      'parentId': [],
      'releaseDate': '2019-03-12',
      'releaseLink': 'https://github.com/SysBioChalmers/Human-GEM/releases/tag/v1.0.0',
      'PMID': 32209698,
      'count': {'reactions': someNum, 'metabolites': someNum, 'genes': someNum},
      'validation': {'pass': someBool}
   },
   {'id': 'Human-GEM-1.1.0'
      'parentId': [{'id': 'Human-GEM-1.0.0', 'citLink': ''],
      'releaseDate': '2019-03-12',
      'releaseLink': 'https://github.com/SysBioChalmers/Human-GEM/releases/tag/v1.1.0',
      'PMID': 32209698,
      'count': {'reactions': someNum, 'metabolites': someNum, 'genes': someNum},
      'validation': {'pass': someBool}
   }
    ...
  ]
},
```

data-files/integrated-models/Mouse-GEM/gemRepository.json

```
{ Mouse-GEM': [
    { 'id': 'Mouse-GEM-1.0.0'
      'parentId': [{'id': 'Human-GEM-1.5.0', 'citLink': 'somePublicationHightlightedSentenceLink'}],
      'releaseDate': '2020-10-24',
      'releaseLink': 'https://github.com/SysBioChalmers/Mouse-GEM/releases/tag/v1.0.0',
      'PMID': 34282017,
      'count': {'reactions': someNum, 'metabolites': someNum, 'genes': someNum},
      'validation': {'pass': someBool}
    },
    { 'id': 'Mouse-GEM-1.1.0'
          'parentId': [{'id': 'Human-GEM-1.5.0', 'citLink': ''}],
          'releaseDate': '2021-01-15',
          'releaseLink': 'https://github.com/SysBioChalmers/Mouse-GEM/releases/tag/v1.1.0',
          'PMID': 34282017,
          'count': {'reactions': someNum, 'metabolites': someNum, 'genes': someNum},
          'validation': {'pass': someBool}
        },
 ...
 ]
}
```

- Keeping a separate gemRepository.json file for each model (which later can be joined into one file/object when the frontend query the api)
- Above is a suggestion on how that file would look like. Note that `count`, `validation` and possible `citLink` data is not intended to be part of the first version of the graph.
- The value of `parentId` is an array since for example Human-GEM is the result of merging multiple models. This is not something we will show in the first version, but it will happen sometime
- `citLink` will be used for major model versions where there is a clear reference in a paper on how that model version is based on another model. An example of this is if you open https://www.ncbi.nlm.nih.gov/pmc/articles/PMC193654/#__p8:~:text=This%20paper%20reports%20an%20expansion%20of,genome%2Dscale%20metabolic%20model%20(iJE660%20GSM)%20%5B8%5D. in Chrome (note that this link is not related to a integrated model but is an example from https://github.com/MetabolicAtlas/tree-of-GEMs/blob/main/editDataset/dataset.json.
- We probably want to have information regarding which publication a version node "belongs" to, We could either just have a PMID with a link, more detailed information (title, authors, year, paper) or skip it depending on how it will look in the drop down when you click a node, there is a risk that it will be too cluttered with too much details. If we want to have detailed information, the PMID can be used in an api query similar to [this](https://github.com/MetabolicAtlas/MetabolicAtlas/blob/c742bfac1de579820378dd46f492fde2c7c05560/frontend/src/api/europepmc.js#L5)


Questions:
- Is this reasonable?
- Should we add getting citLink data to #954 or create a new issue and add it in a later version of the graph? Since there are so few models in this first version I think it should not take too much time to find the relevant sentences and thus be part of #954

**Comment by MalinAhlberg** [comment]
Very nice examples, and good research @inghylt ! I think it looks really nice!
Two minor things:
- we discussed having a field for `major`/`minor`, so that it can be set manually when needed. Maybe you decided against that last week?
- if each model has its own file, can't we drop the outer object (with eg `Mouse-GEM` as the key) and just keep the list?
So that `data-files/integrated-models/Mouse-GEM/gemRepository.json` looks like
```json
[
    { 'id': 'Mouse-GEM-1.0.0',
      'parentId': [{'id': 'Human-GEM-1.5.0', 'citLink': 'somePublicationHightlightedSentenceLink'}],
     ...
]
```

**Comment by nanjiangshu** [comment]
Great work @inghylt! I think most of the stuff are already included in the example you provided. Below I list some of my comments
1. I'm a bit confused with this sentence `Keeping a separate gemRepository.json file for each model (which later can be joined into one file/object when the frontend query the api)`. If the files will be joined into one file why bother store them separately. I guess you  mean joining the data into one object when these files are read in to the database. 
I'm OK to store them either separately or in one file. If separately, I think we can ignore the first level key as @MalinAhlberg pointed out.

2. I think it is a bit unreliable to determine whether a release is `major` or `minor` based on the value of `citLink`. I agree with Malin again that it is better to have a key e.g. 
`majorRelease: true|false`. I'm not sure if every major releases for all GEMs has a corresponding publication. If not, then the value of `citLink` might be empty. We may add additional information related to a given major release, not limited to `citLink`.
Moreover, I think it might be enough to provide just the PMID in order to get the information about a publication. Since each release has already provided with a PMID, `citLink` might be duplicated. We may however provide additional release info as e.g. `releaseInfo` so that more details can be shown (if needed) for a major release.

**Comment by inghylt** [comment]
@MalinAhlberg @nanjiangshu 

- Since all the models follow major.minor.patch in their releases, I think it is redundant to have a property for major vs minor as we can deduce this programmatically. 
- `citLink` will be used to show how a model node has branched off another one, e.g. that Mouse-GEM 1.0.0 is based on Human-GEM-1.5.0. It will contain reference to a specific sentence in a paper to highlight this relationship. As mention above, open [this link](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8325244/#__p7:~:text=In%20this%20pipeline%2C%20the%20open%2Dcurated%20generic%20human%20GEM%2C%20Human1%20(11)%2C%20was%20used%20as%20a%20template) in Chrome for an example. Thus, citLink is needed as PMID can't contribute this information. 
- I think it makes sense to have separate files for each model, since we might want to incorporate more models in the future that belong to category B) and D). I think it makes sense to have the model as the outer key since we we will join the data into one main object

**Comment by nanjiangshu** [comment]
> @MalinAhlberg @nanjiangshu
> 
>     * Since all the models follow major.minor.patch in their releases, I think it is redundant to have a property for major vs minor as we can deduce this programmatically.

I'm not quite sure if all GEMs follow the pattern `major.minor.patch`.  If that is true, for `Human-GEM`, I would guess the only major release is `1.0.0`, but if you look at the release note, it does not look like a major release at all. Moreover, what about the releases that changed the format of the `ID` by using MA IDs (in 1.8.0) and the columns of `TSV` files (in 1.7.0) ?
 
> 
>     * `citLink` will be used to show how a model node has branched off another one, e.g. that Mouse-GEM 1.0.0 is based on Human-GEM-1.5.0. It will contain reference to a specific sentence in a paper to highlight this relationship. As mention above, open [this link](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8325244/#__p7:~:text=In%20this%20pipeline%2C%20the%20open%2Dcurated%20generic%20human%20GEM%2C%20Human1%20(11)%2C%20was%20used%20as%20a%20template) in Chrome for an example. Thus, citLink is needed as PMID can't contribute this information.

I see. Then it is probably good to have. However, it seems this link does not work for Firefox nor for Safari. 
Also, I'm not sure if every branching has a corresponding  `citLink`. 
> 
>     * I think it makes sense to have separate files for each model, since we might want to incorporate more models in the future that belong to category B) and D). I think it makes sense to have the model as the outer key since we we will join the data into one main object

I'm OK to store these information as separate files but was just confused when you mentioned to combine these files into one file later on. No problem to keep the outer key as well.

**Comment by inghylt** [comment]
@nanjiangshu 

- > I'm not quite sure if all GEMs follow the pattern major.minor.patch. If that is true, for Human-GEM, I would guess the only major release is 1.0.0, but if you look at the release note, it does not look like a major release at all. Moreover, what about the releases that changed the format of the ID by using MA IDs (in 1.8.0) and the columns of TSV files (in 1.7.0) ?

   As I have understood it from @mihai-sysbio, we should just follow the release versioning. You do raise a valid point though, but I think it would be tedious for us to manually decide which should be major and minor and counterintuitive for users if MetAtlas don't follow the released version of the models. To me, fixing what should be major or not should be on SysBio side, not MetAtlas. @mihai-sysbio what are your opinion on this?
- All the integrated models except yeast are branched on Human-Gem, as seen in the [figma](https://www.figma.com/file/0KIii23icCOgACJiodqbqv/History-of-GEM%3As?node-id=0%3A1) and [the paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8325244/). That the Human-Gem version used was 1.5.0 is based on [this link](https://www.pnas.org/action/downloadSupplement?doi=10.1073%2Fpnas.2102344118&file=pnas.2102344118.sapp.pdf) which was provided by @mihai-sysbio in Slack 
- `citLink` highlighting does only work on Chrome yes. This is a functionality suggested by @mihai-sysbio so I guess he believes there are enough users of Chrome and that other web browser users are able to find what they need in the paper without the highlighted sentence

**Comment by mihai-sysbio** [comment]
> just follow the release versioning

> fixing what should be major or not should be on SysBio side, not MetAtlas

Solid reasoning 🦉 while @nanjiangshu's feedback is valid, it's beyond us in Metabolic Atlas to decide what is "major".

Here is more info on the text highlighting https://wicg.github.io/scroll-to-text-fragment/

**Comment by inghylt** [comment]
Summary:

@MalinAhlberg @mihai-sysbio @nanjiangshu @shan-chalmers @perjo 
After the discussions in the comments and live yesterday, here is hopefully the final suggestion:

data-files/integrated-models/Human-GEM/gemRepository.json
```
{ 'id': 'Human-GEM-1.0.0'
      'parentId': [],
      'releaseDate': '2019-03-12',
      'releaseLink': 'https://github.com/SysBioChalmers/Human-GEM/releases/tag/v1.0.0',
      'PMID': 32209698,
      'count': {'reactions': someNum, 'metabolites': someNum, 'genes': someNum},
      'validation': {'pass': someBool}
},
{'id': 'Human-GEM-1.1.0'
      'parentId': [{'id': 'Human-GEM-1.0.0', 'citLink': ''}],
      'releaseDate': '2019-03-12',
      'releaseLink': 'https://github.com/SysBioChalmers/Human-GEM/releases/tag/v1.1.0',
      'PMID': 32209698,
      'count': {'reactions': someNum, 'metabolites': someNum, 'genes': someNum},
      'validation': {'pass': someBool}
}
...
```

data-files/integrated-models/Mouse-GEM/gemRepository.json

```
{ 'id': 'Mouse-GEM-1.0.0'
      'parentId': [{'id': 'Human-GEM-1.5.0', 'citLink': 'somePublicationHightlightedSentenceLink'}],
      'releaseDate': '2020-10-24',
      'releaseLink': 'https://github.com/SysBioChalmers/Mouse-GEM/releases/tag/v1.0.0',
      'PMID': 34282017,
      'count': {'reactions': someNum, 'metabolites': someNum, 'genes': someNum},
      'validation': {'pass': someBool}
},
{ 'id': 'Mouse-GEM-1.1.0'
          'parentId': [{'id': 'Mouse-GEM-1.0.0', 'citLink': ''}],
          'releaseDate': '2021-01-15',
          'releaseLink': 'https://github.com/SysBioChalmers/Mouse-GEM/releases/tag/v1.1.0',
          'PMID': 34282017,
          'count': {'reactions': someNum, 'metabolites': someNum, 'genes': someNum},
          'validation': {'pass': someBool}
}
...
```

- Keeping a separate gemRepository.json file for each model (which later can be joined into one object when the frontend query the api)
- The value of `parentId` is an array since for example Human-GEM is the result of merging multiple models. This is not something we will show in the first version, but it will happen sometime
- We will handle distinguishing between major vs minor in the frontend code based on the version number
- `citLink` will be used for model versions where there is a clear reference in a paper on how that model version is based on another model, i.e. the relationship between the two nodes will be "decorated" with this. Open https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8325244/#__p7:~:text=In%20this%20pipeline%2C%20the%20open%2Dcurated%20generic%20human%20GEM%2C%20Human1%20(11)%2C%20was%20used%20as%20a%20template. in Chrome for an example (this is inspired from `citLink` in https://github.com/MetabolicAtlas/tree-of-GEMs/blob/main/editDataset/dataset.json).
- We probably want to have information regarding which publication a version node "belongs" to, We could either just have a PMID with a link, more detailed information (title, authors, year, paper) or skip it depending on how it will look in the drop down when you click a node, there is a risk that it will be too cluttered with too much details. If we want to have detailed information, the PMID can be used in an api query similar to [this](https://github.com/MetabolicAtlas/MetabolicAtlas/blob/c742bfac1de579820378dd46f492fde2c7c05560/frontend/src/api/europepmc.js#L5)

**Comment by nanjiangshu** [comment]
Great summary @inghylt! I would like to add one point and clarify another point
* One point to be added: pre-releases will not be included 
* One point which I'm not clear: should every node has a `parentId`? Or we just add a `parentId` when there is a valid `citLink` while for the rest of releases the parent will be set as the nearest previouse release for the same GEM?

**Comment by e0** [comment]
**Approved**

This looks great @inghylt!

It's nice that we are considering the data needed for later on. For the near future it looks like we won't be needing the `count` and `validation` fields. I think there is a good possibility that we would need to revise some things when working on the data collection issue. So personally I'm happy with the state of this issue and think it could be closed.

**Comment by inghylt** [comment]
Summary:

@MalinAhlberg @mihai-sysbio @nanjiangshu @shan-chalmers @perjo 
Hopefully the final suggestion, updated parentId section as discussed

data-files/integrated-models/Human-GEM/gemRepository.json
```
{ 'id': 'Human-GEM-1.0.0'
      'externalParentId': [],
      'releaseDate': '2019-03-12',
      'releaseLink': 'https://github.com/SysBioChalmers/Human-GEM/releases/tag/v1.0.0',
      'PMID': 32209698,
      'count': {'reactions': someNum, 'metabolites': someNum, 'genes': someNum},
      'validation': {'pass': someBool}
},
{'id': 'Human-GEM-1.1.0'
      'externalParentId': [],
      'releaseDate': '2019-03-12',
      'releaseLink': 'https://github.com/SysBioChalmers/Human-GEM/releases/tag/v1.1.0',
      'PMID': 32209698,
      'count': {'reactions': someNum, 'metabolites': someNum, 'genes': someNum},
      'validation': {'pass': someBool}
}
...
```

data-files/integrated-models/Mouse-GEM/gemRepository.json

```
{ 'id': 'Mouse-GEM-1.0.0'
      'externalParentId': [{'id': 'Human-GEM-1.5.0', 'citLink': 'somePublicationHightlightedSentenceLink'}],
      'releaseDate': '2020-10-24',
      'releaseLink': 'https://github.com/SysBioChalmers/Mouse-GEM/releases/tag/v1.0.0',
      'PMID': 34282017,
      'count': {'reactions': someNum, 'metabolites': someNum, 'genes': someNum},
      'validation': {'pass': someBool}
},
{ 'id': 'Mouse-GEM-1.1.0'
          'externalParentId': [],
          'releaseDate': '2021-01-15',
          'releaseLink': 'https://github.com/SysBioChalmers/Mouse-GEM/releases/tag/v1.1.0',
          'PMID': 34282017,
          'count': {'reactions': someNum, 'metabolites': someNum, 'genes': someNum},
          'validation': {'pass': someBool}
}
...
```

- Keeping a separate gemRepository.json file for each model (which later can be joined into one object when the frontend query the api)
- The value of `parentId` is an array since for example Human-GEM is the result of merging multiple models. This is not something we will show in the first version, but it will happen sometime
- We will handle distinguishing between major vs minor in the frontend code based on the version number
- `citLink` will be used for model versions where there is a clear reference in a paper on how that model version is based on another model, i.e. the relationship between the two nodes will be "decorated" with this. Open https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8325244/#__p7:~:text=In%20this%20pipeline%2C%20the%20open%2Dcurated%20generic%20human%20GEM%2C%20Human1%20(11)%2C%20was%20used%20as%20a%20template. in Chrome for an example (this is inspired from `citLink` in https://github.com/MetabolicAtlas/tree-of-GEMs/blob/main/editDataset/dataset.json).
- We probably want to have information regarding which publication a version node "belongs" to, We could either just have a PMID with a link, more detailed information (title, authors, year, paper) or skip it depending on how it will look in the drop down when you click a node, there is a risk that it will be too cluttered with too much details. If we want to have detailed information, the PMID can be used in an api query similar to [this](https://github.com/MetabolicAtlas/MetabolicAtlas/blob/c742bfac1de579820378dd46f492fde2c7c05560/frontend/src/api/europepmc.js#L5)

**Comment by nanjiangshu** [comment]
Thanks for the updated summary @inghylt. It looks great to me and I can approve it.

**Comment by e0** [comment]
LGTM

**Comment by MalinAhlberg** [comment]
:+1:
