### ISSUE TITLE
limit in api search query is not working as expected

### ISSUE THREAD

**Issue by MalinAhlberg** [MetabolicAtlas/MetabolicAtlas#968]
**Describe the bug**

**Steps to reproduce**

- Use the api to search with `limit` set to 20, eg `/search?searchTerm=Retinol+metabolism&model=HumanGem&version=1_10_0&limit=20`
- Note that there are 19 metabolites returned, 6 genes etc. The total count is > 20, but each component seems to be limited to <20 hits.
- Do the same search with `limit` 2.
- Note that you get 1 metabolite and 1 subsystem, but 0 for all others, including genes . The total count is now 2, and each component has < 2 hits, sometimes less even when there are hits to be shown.

**Expected behavior**

- [ ] The `limit` should be either by component or in total, and work consistently 
- [ ] Tests verifying the fix are added

**Comment by nanjiangshu** [comment]
After looking at this issue. I find it might be tricky to let the number of components, either individually or in total, be identical to the `limit` 

This is because the current searching is carried out by first retrieving all nodes with the keyword searching and from that a list of unique IDs will be generated. After that, these unique IDs will be grouped by components and each group of IDs will be used to fetch nodes for respective components separately. The `limit` is only set at the first step.  That is, the number of nodes retrieved at the first step will be equal to the value of `limit` or the total number of nodes found by the searchTerm. At the second step, the number of items retrieved for each component is <= `limit` or total number in the database. This means the total number of retrieved items of all components are between in the range of `[0, num_component x limit]`

I have tried to increase the limit of the first step searching, for example, change the code https://github.com/MetabolicAtlas/MetabolicAtlas/blob/main/api/src/neo4j/queries/search/modelSearch.js#L51 to 
```javascript
LIMIT ${limit*2+50}
```
and then add 
```
LIMIT ${limit}
```
to each individual component searching. By doing so, in most cases, the number of retrieved items for each component will be equal to the value of `limit`.

However, I don't think this is a good solution, firstly, this slow down the searching performance; and secondly, it can not guarantee that the number of retrieved items of each component is euqal to the value of `limit`.

What is your opinion? Should we make the changes or just leave it as is and add a comment somewhere that this limit is set only for the first step of searching?

**Comment by e0** [comment]
After looking into this a bit now, I realized that the problem with `metabolites` limit was only partially fixed before.

Initially when the `limit` was `50`, it was possible to get more than 50 `metabolites` (due to connected compartmentalized metabolites). We "fixed" that by passing the `limit` of 50 when fetching `metabolites`. However as described in this issue, this could still cause the total number of results to exceed the `limit`.

I think instead of passing the provided `limit` (50) to the `fetchCompartmentalizedMetabolites` function, we should actually be passing the sum of the lengths of `groupedByComponents['CompartmentalizedMetabolite']` and `groupedByComponents['Metabolite']`. This way the total number of results should never exceed the provided `limit`.

**Comment by e0** [comment]
To follow up the last comment, currently there is a mismatch of what is shown in the frontend and what we return in the backend and that can cause confusion for both the users and developers.

In the frontend, the text "Limited to 10 results per type" is displayed. This makes it seem like the `limit` provided to the backend should be per type. Instead, the backend is actually implemented for the `limit` to be for all results regardless of type. To avoid this confusion and to make the frontend better reflect actual search results, I propose that we apply the change in the backend as mentioned in [the previous comment](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/968#issuecomment-1229906621), then in the frontend we stop limiting to 10 per type and change the text "Limited to 10 results per type" to "Limited to 50 results".

Please let me know if this makes sense and we should go ahead with it.

**Comment by nanjiangshu** [comment]
I think it makes sense to change the notification in the frontend since it reflects how searching actually works. The limit set on the frontend can then be removed.

**Comment by nanjiangshu** [comment]
Hi @e0 , I took another look at this issue and realized by showing all results fetched from the backend with `Limited to 50 results` might not be ideal neither. For example, when searching for `acid`, it returns 49 genes and 2 metabolites. The result table will be too overwhelmed by the genes hits if we shown them all in the quick search mode. 

In addition, setting the limit of `fetchCompartmentalizedMetabolites()` as the sum of the lengths of  `groupedByComponents['CompartmentalizedMetabolite'] and groupedByComponents['Metabolite']` does  ensures the total number of hits <= 50. However, this is achieved at the cost of reducing the number of metabolite hits. I'm not sure if this is what we want. Take the same example, when searching for `acid`, there are 2 metabolites hits before, but if we set the limit to   `(groupedByComponents['CompartmentalizedMetabolite'] || []).length + (groupedByComponents['Metabolite'] || []).length,`, only 1 metabolites hit is returned. Why should  just metabolites be filtered but not others.

**Comment by e0** [comment]
> Hi @e0 , I took another look at this issue and realized by showing all results fetched from the backend with `Limited to 50 results` might not be ideal neither. For example, when searching for `acid`, it returns 49 genes and 2 metabolites. The result table will be too overwhelmed by the genes hits if we shown them all in the quick search mode.

@nanjiangshu For this example, if we prefer to show 10 genes and 2 metabolites instead of 48 genes and 2 metabolites, that is fine. I don't have a strong opinion on this but if I would vote I would stil go for 48 genes and 2 metabolites.

I think not doing anything is fine here. We just have to acknowledge that if this is the desired state, it's a side-effect of buggy implementation in the backend.

---

> Why should just metabolites be filtered but not others.

That's a good point. I guess to do this in the most correct way, we should not pass any `limit` at all to the `fetchCompartmentalizedMetabolites` function. Then once we get all the results back, say that there are 30 metabolites and 30 of other types (genes, reactions etc), we sort all of the results again by match score (from full text search) and then retrieve the top 50. This way we are not discriminating against other types and all results are returned according to the match score.

**Comment by nanjiangshu** [comment]
For the GemSearch, we show that `Limited to 10 results per type` but actually we are limiting the total number of hits (of all components) to 50 when retrieving the results from the API. So here is the question, shall we show all results (<=50) retrieved from the API or after another layer of filtering and show <=10 results per component? 

The current implementation that adds limit per type does not reflect the actual found results sorted by matching score but may avoid the cases where the results are dominated by one type. 
 
You can play with the version which shows all retrieved result at this server http://134.158.151.84/ as compared to https://metabolicatlas.org/ 

Any opinions @JonathanRob @Benfeitas @mihai-sysbio?

**Comment by mihai-sysbio** [comment]
Conceptually top 50 would sound alright, but trying a keyword such as `fatty` gives more usable results on the current implementation at metabolicatlas.org. Therefore, I think we should continue with the binning of the results.
