### ISSUE TITLE
Update model versions

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#970]
**Please describe the feature**

As a user I want to have the latest GEM releases at MetAtlas so that I work with the latest data.

**Acceptance Criteria**

- [ ] An updated database, at least Mouse-GEM and Human-GEM, by copying files from each GEM repo (model.yml and *.tsv in the `/model` folder)
- [ ] The API response is the same as before
- [ ] Test/script that indicates which models need updating (this might overlap with code in data-files)
- [ ] Update documentation on how to run the update process

**Additional context**

**Comment by inghylt** [comment]
Note that as of 3/5 all models needs an update

**Comment by nanjiangshu** [comment]
I was originally trying to update all mode files with a script, however, subtle errors in the model file such as https://github.com/SysBioChalmers/Fruitfly-GEM/issues/7 cost lots of time to debug. Have to update the models one by one manually.

**Comment by mihai-sysbio** [comment]
Thanks for creating that issue @nanjiangshu. I'm wondering what the fastest way to a fix is. From what I'm seeing in that issue, it looks like the problems can be solved by manually correcting the file without affecting the model content. What do you think?

**Comment by nanjiangshu** [comment]
Hi @mihai-sysbio, @inghylt @e0 and @MalinAhlberg. I have updated 6 integrated models by small modifications in the YAML files, but the Yeast-GEM is still failed to update, and it took longer time than I thought. 
My general impression from model updating is that we should have a clearer guideline about how the metaData of the models should be defined as @haowang-bioinfo also questioned in his comment https://github.com/SysBioChalmers/Fruitfly-GEM/issues/7#issuecomment-1128588157. 

1. What should be the format of the `short_name`? The current code assumes the `short_name` should be in the format of `Fruitfly-GEM` but what about its variations? Can it be 
`fruitflyGem` or `fruitflygem` or `FRUITFLY-Gem` or `Fruitfly GEM`? It doesn't matter if many formats are allowed since we can modify the code to deal with it, but it should be defined.


2. It is unclear what should be the minimum items with values in the `metaData`. For example, the item `version` is set in some of the releases and this value is required now in the parsing code. But in the latest releases for most models the value of `version` is empty. Should this item always be defined or should the file `version.txt` be used instead? 

The model that I failed to update so far is `Yeast-GEM` since the entry for subsystem is missing from the version `8.5.0` and `8.6.0`. For the version `8.6.0`, the item subsystem is there but the value is empty, while for the version `8.5.0`, `subsystem` is totally missing. I'm not sure if this is expected. If we use these two releases for Yeast-GEM, none of the SVG maps for subsystems will be shown.

There is also a minor thing about the `Yeast-GEM`, the model file is named as `yeast-GEM.yml` in SysBio and `yeastGEM.yml` in `data-files`. In contrast, all the rest of the model files have the first letter capitalized, e.g. `Human-GEM`. I'm not sure if there is any special reason for that.

**Comment by mihai-sysbio** [comment]
If changes are made to the YAML files, those should be (also) reported as issues in the source repositories (as you did with Fruitfly-GEM).
The metadata is an unstructured field that has no standard equivalent. Of course it would be great to have a clearer guideline, but it's also not something we can immediately impose.
1. So far, it's acceptable to have the code set up for `short_name` ending in `-GEM`.
2. My suspicion is that it's by accident that the version is missing. The `version.txt` file serves a different purpose, and it's a different file, so I'm not sure how looking at that would help.

The subsystems in yeast-GEM have been updated recently so I would have to look more into that.

It's a historical reason, should be like the original in data-files as well: `yeast-GEM`.

**Comment by haowang-bioinfo** [comment]
> 1. So far, it's acceptable to have the code set up for short_name ending in -GEM.

the [removal](https://github.com/SysBioChalmers/Fruitfly-GEM/blob/76378e885bacaa9bbc7e1d390861daec3dd0dcfe/code/masterScriptFruitflyGEM.m#L48) of hyphen was for proper export of `xml` file, and can be fixed later. But would it easier to allow any given character string provided by `short_name`?

> 2. My suspicion is that it's by accident that the version is missing. The version.txt file serves a different purpose, and it's a different file, so I'm not sure how looking at that would help.

the version value probably is missing from all model animal GEMs, and the fix would be a generic function
